### ISSUE TITLE
bug in column filter?

### ISSUE THREAD

**Issue by andreassteffen** [Caleydo/lineupjs#234] opened 2017-04-04 07:40 UTC
when using the column filter, e.g. via regexp ^B and afterwards deleting it again
not all rows are coming back. seems like the filter is not completely removed.

**Comment by sgratzl** [comment] 2017-04-11 10:48
can't reproduce
![gif](https://cloud.githubusercontent.com/assets/4129778/24905713/21f41022-1eb5-11e7-9743-0c6055633d04.gif)

**Comment by sgratzl** [comment] 2017-06-08 09:38
issue: 
 * happens in the react binding with SVG renderer
 * after resetting the filter the scrollbars on the right have the right size but the corresponding rows aren't rendered below the previous visible ones
 * so a lot of white space without rendered rows
 * when triggering a reordering -> everything back to normal

**Comment by thinkh** [comment] 2018-06-29 12:45
@sgratzl Is this still in issue with the new implementation?

**Comment by thinkh** [comment] 2018-11-26 16:09
In my quick test this is fixed in LineUp v4.0.0-alpha.8.

**Closed by thinkh** 2018-11-26 16:09 UTC
Labels: priority: medium, type: bug
