### ISSUE TITLE
clean up offered visualization types

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#362] opened 2017-10-11 11:29 UTC
at the moment, visualization for columns are offered that don't work (e.g., sparkline, etc.). I suggest to remove or implement them. In the end, only visualizations should show up that make sense and work.

this needs to be done for categorical, numerical and matrix columns - in item and group mode.

**Comment by sgratzl** [comment] 2017-10-11 12:57
fixed sparkline and other multi value renderer:

![2017-10-11 14_56_35-lineup alpha](https://user-images.githubusercontent.com/4129778/31441723-6c50dfaa-ae94-11e7-8bfe-f77db2793d25.png)

**Comment by thinkh** [comment] 2017-10-20 16:14
Done with / duplicate of #401.

**Closed by thinkh** 2017-10-20 16:14 UTC
Labels: priority: medium, type: aesthetics
